config/routes.rb
Lalala::Application.routes.draw do

  get "signout" => "sessions#destroy"
  get "signin" => "sessions#new"
  get "signup" => "users#new", :as => "signup"

  root to: "static_pages#home"

  resources :users

  resources :sessions

  resources :photos, only: [:new, :create]
  get '/photos/new_multiple', to: 'photos#new_multiple', as: :new_photo_multiple

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new


    if user.role?('super_admin')
      can :manage, :all
    elsif user.admin?
      can :manage, User
     else
      can [:create, :new, :edit,:show, :update], User
    end
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  dragonfly_accessor :image
  validates :image, presence: true
  validates_size_of :image, maximum: 500.kilobytes,
                    message: "should be no more than 500 KB", if: :image_changed?
  validates_property :format, of: :image, in: [:jpeg, :jpg, :png, :bmp], case_sensitive: false,
                     message: "should be either .jpeg, .jpg, .png, .bmp", if: :image_changed?
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name

  has_one :users
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :name, :surname,  :email, :password,  :password_confirmation, :role_id, :upload_id, :avatar
  attr_accessor :password, :password_confirmation
  has_attached_file :avatar,  :styles => { :small => "150x150>" }



  before_save { |user| user.email = email.downcase }
  before_save :encrypt_password

  belongs_to :role
  belongs_to :photo

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
            format:     { with: VALID_EMAIL_REGEX }
          #  uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 1 }
  validates :password_confirmation, presence: true
  validates_attachment :avatar,
                      # :presence => true,
                       :size => { :in => 0..10.megabytes },
                       :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/}



  def super_admin?
    ["super_admin"].include? self.role.try(:name)
  end


  def admin?
    ["admin", "super_admin"].include? self.role.try(:name)
  end

  def role?(role)
    ["super_admin"].include? self.role.try(:name)
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end


  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user


private

  def current_ability
    @current_ability ||= Ability.new(current_user)
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def new_multiple
    @photos = Photo.order('created_at DESC')
    @photo = Photo.new
  end

  def create
    respond_to do |format|
      @photo = Photo.new(photo_params)
      @photo.save
      format.html { redirect_to new_photo_path }
      format.js
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:image, :author)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if user = User.authenticate(params[:session][:email], params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user), :notice => ""
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => ""
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  respond_to :html, :js

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def index
    @users = User.order("name").page(params[:page]).per(4)
  end

  def create
   @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = ""
      redirect_to @user
    else
      render 'new'
    end
  end


  def edit
    @user = User.find(params[:id])

  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to (@user) }
        format.js
      else
        format.html { render :action => "edit" }
        format.js
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to :back}
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :surname, :avatar, :password, :password_confirmation)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user == user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user == nil
    cookies.delete(:remember_token)
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container" style="padding: 0 150px;">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <b class="navbar-brand"><%=link_to "Project", root_path %></b>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
            <li><%= link_to "Home", current_user %></li>
            <li><%= link_to "Edit",   edit_user_path(current_user) %>
            <li><%= link_to 'Upload photos', new_photo_multiple_path %></li>
            <%if current_user.admin? %>
            <li><%= link_to "Users", users_path %></li>
            <% end %>
            <li><%= link_to "Sign out", signout_path %></li>
        <% else %>
            <li><%= link_to "Sign in", {}, remote: true, data: {toggle:'modal', target:'#Mymodal'} %></li>

        <% end %>
      </ul>

    </div><!--/.nav-collapse -->
  </div>
</nav>
<%= render 'sessions/modal' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true%>
  <%= javascript_include_tag 'jquery' %>
  <%= csrf_meta_tags %>

  <link href="../assets/css/bootstrap.css" rel="stylesheet">
  <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">
  <script data-turbolinks-track="true" src="https://sitepoint-async-upload.herokuapp.com/assets/application-441a5e3fe5e3fd874d440d2eea208cfc.js"></script>


  <style type="text/css">body{padding-top:60px;padding-bottom:40px;}.row{margin: 0 !important;}#footer{height:60px;background-color:#f5f5f5;margin: 50px 0 !important;}@media (max-width: 767px) {#footer{margin-left:-20px;margin-right:-20px;padding-left:20px;padding-right:20px;}}.credit{margin:20px 0;}</style>

</head>
<body>

<%= render 'layouts/nav' %>
<div class="container">
  <div class="row">
    <div class="">
      <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <div id="content">
        <%= yield %>
      </div>
    </div>
  </div>
</div>




  <div id="footer" >
    <div class="container" style="padding: 0 150px;">
      <p class="muted credit">creator Natasha<br>
        email: noli.pogorelova@gmail.com
      </p>
    </div>
  </div>



</body>
</html>

app/views/photos/_photos.html.erb
<li class="col-xs-3">
  <%= link_to image_tag(photo.image.thumb('180x180#').url, alt: photo.image_name, class: 'img-thumbnail'),
              photo.image.remote_url, target: '_blank' %>
  <% if photo.image_name.present? %>
      <p><%= photo.image_name %></p>
  <% end %>
</li>

app/views/photos/create.js.erb
<% if @photo.new_record? %>
alert('<%= @photo.image_name %> could not be uploaded: <%= j @photo.errors.full_messages.join(',
').html_safe %>');
<% else %>
$('#photos-list').prepend('<%= j render @photo %>');
<% end %>

app/views/photos/new_multiple.html.erb
<h1>List of photos</h1>
<ul class="row" id="photos-list">
  <%= render @photos %>
</ul>
<h3>Upload multiple photos</h3>
<div id="dropzone" class="fade">Drop files here</div>
<%= form_for @photo do |f| %>
    <div class="form-group">
      <%= f.label :image, 'Choose files here' %>
      <%= f.file_field :image, required: true, multiple: true, name: 'photo[image]' %>
    </div>
    <div class="progress-wrapper">
      <p>Bitrate: <span class="bitrate"></span></p>
      <div class="progress">
        <div class="progress-bar" role="progressbar">
          0%
        </div>
      </div>
    </div>
<% end %>
<script>
    $(document).ready(function() {
        var multiple_photos_form = $('#new_photo');
        var wrapper = multiple_photos_form.find('.progress-wrapper');
        var bitrate = wrapper.find('.bitrate');
        var progress_bar = wrapper.find('.progress-bar');
        multiple_photos_form.fileupload({
            dataType: 'script',
            dropZone: $('#dropzone'),
            add: function (e, data) {
                types = /(\.|\/)(gif|jpe?g|png|bmp)$/i;
                file = data.files[0];
                if (types.test(file.type) || types.test(file.name)) {
                    data.submit();
                }
                else { alert(file.name + " must be GIF, JPEG, BMP or PNG file"); }
            }
        });
        multiple_photos_form.on('fileuploadstart', function() {
            wrapper.show();
        });
        multiple_photos_form.on('fileuploaddone', function() {
            wrapper.hide();
            progress_bar.width(0);
        });
        multiple_photos_form.on('fileuploadsubmit', function (e, data) {
            data.formData = {'photo[author]': $('#photo_author').val()};
        });
        multiple_photos_form.on('fileuploadprogressall', function (e, data) {
            bitrate.text((data.bitrate / 1024).toFixed(2) + 'Kb/s');
            var progress = parseInt(data.loaded / data.total * 100, 10);
            progress_bar.css('width', progress + '%').text(progress + '%');
        });
        $(document).bind('dragover', function (e) {
            var dropZone = $('#dropzone'),
                    timeout = window.dropZoneTimeout;
            if (!timeout) {
                dropZone.addClass('in');
            } else {
                clearTimeout(timeout);
            }
            var found = false,
                    node = e.target;
            do {
                if (node === dropZone[0]) {
                    found = true;
                    break;
                }
                node = node.parentNode;
            } while (node != null);
            if (found) {
                dropZone.addClass('hover');
            } else {
                dropZone.removeClass('hover');
            }
            window.dropZoneTimeout = setTimeout(function () {
                window.dropZoneTimeout = null;
                dropZone.removeClass('in hover');
            }, 100);
        });
    });
</script>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/static_pages/home.html.erb
<div >
  <center>
  <h1 class="line">Welcome</h1> <br>
  <br>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %><br><br>
  </center>

</div>

app/views/users/_modal.html.erb
<div id="loginModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Edit profile </h4>
      </div>
      <% provide(:title, "Edit user") %>
      <div class="modal-body">
        <%= form_for @user, :url => users_path, :html => { :multipart => true } do |f| %>
            <%= render 'shared/error_messages' %>
            <%= f.label :name %>
            <%= f.text_field :name %>

            <%= f.label :surname %>
            <%= f.text_field :surname %>

            <%= f.label :email %>
            <%= f.text_field :email %>

            <%= f.label :password %>
            <%= f.password_field :password %>

            <%= f.label :password_confirmation, "Confirm Password" %>
            <%= f.password_field :password_confirmation %>

            <%=f.label :avatar, "Avatar:" %>
            <%= f.file_field :avatar%>

            <div class="clear"></div>
      </div>
      <div class="modal-footer">
        <%= f.submit "Save changes", class: "btn btn-large btn-success" %>
        <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_modal_edit.html.erb
<div id="MyModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><h1> Edit profile </h1></h4>
      </div>
      <% provide(:title, "Edit user") %>
      <div class="modal-body">
        <%= form_for @user, remote: true, html: { multipart: :true } do |f| %>

            <%= render 'shared/error_messages' %>
            <%= f.label :name %>
            <%= f.text_field :name %>

            <%= f.label :surname %>
            <%= f.text_field :surname %>

            <%= f.label :email %>
            <%= f.text_field :email %>

            <%= f.label :password %>
            <%= f.password_field :password %>

            <%= f.label :password_confirmation, "Confirm Password" %>
            <%= f.password_field :password_confirmation %>
            <div class="clear"></div>
            </div>
            <div class="modal-footer">
              <%= f.submit "Save changes", class: "btn btn-large btn-success" %>
            </div>
        <% end %>
      </div>
  </div>
</div>

app/views/users/_user.html.erb
<li>

  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
                    data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/_users.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%= will_paginate @users %>

app/views/users/destroy.js.erb
$('#user_<%= @user.id %>').remove();
$('#content').html(<%= j render 'index'%>)

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<div class="row">
 <!-- <div class="col-md-3 col-md-offset-4">-->
    <h1 class="line1"> <center> Edit profile </center></h1>
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <center>
          <div style="margin-bottom: 25px;" class="  col-md-3 col-md-offset-0 input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
          </div>

          <div style="margin-bottom: 25px" class="col-md-3 col-md-offset-0 input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%= f.text_field :surname, class: "form-control", placeholder: "Surname" %>
          </div>

          <div style="margin-bottom: 25px" class="col-md-3 col-md-offset-0 input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
            <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
          </div>

          <div style="margin-bottom: 25px" class="col-md-3 col-md-offset-0 input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
            <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
          </div>

          <div style="margin-bottom: 5px" class="col-md-3 col-md-offset-0 input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password confirmation" %>
          </div>

          <div style="margin-bottom: 15px"  class=" glyphicon glyphicon-paperclip">
            <%= f.label :avatar, "Avatar:" %>
            <%= f.file_field :avatar%>
          </div>


          <%if current_user.super_admin? %>
              <div>
                <%= f.select :role_id, options_from_collection_for_select(Role.all, 'id', 'name')%>
              </div>
          <% end %>

          <%= f.submit "Save changes", class: "btn btn-large btn-success" %>
        </center>


        <%if current_user.admin? %>
            <div style= "float:right;margin-right:30%;">
              <%= link_to 'Back', users_path, class: "btn btn-small btn-primary" %>
            </div>
        <%end%>

    <% end %>

</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1 style="color:#FFA07A ; font-size:55px;"> <center> All users </center> </h1>

<ul class="users">
  <section>


    <%=paginate  @users%>
    <br>
    <% @users.each do |user| %>
        <% if !user.super_admin? %>
            <%#= image_tag user.avatar.url(:small) %>
            <% if user.admin?%>
                <p>
                  Admin:
                  <%= user.name %>
                </p>
                <% else %>
                <%= user.name %>
             <% end %>
            <%= user.surname %>

            <%= link_to 'Show', user,  class: "btn  btn-small btn-warning " %>
            <%= link_to 'Edit',  edit_user_path(user) ,  class: "btn btn-small btn-success" %>

            <%= link_to 'Destroy', user, method: :delete,
                        data: { confirm: 'Are you sure?' },
                        class: " btn btn-small btn-danger" %>
            <br>
            <%= user.email %>
            <br>
        <% end %>
    <%end%>

  </section>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
  <div class="col-md-3 col-md-offset-4">
    <h1> Sign up </h1>

    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <div style="margin-bottom: 25px" class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
        <%= f.text_field :name, class: "form-control", placeholder: "Name"%>
        </div>

        <div style="margin-bottom: 25px" class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
          <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
        </div>

        <div style="margin-bottom: 25px" class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
          <%= f.password_field :password,  class: "form-control", placeholder: "Password" %>
        </div>

        <div style="margin-bottom: 25px" class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
        <%= f.password_field :password_confirmation,  class: "form-control", placeholder: "Password Confirmation" %>
        </div>

        <div style="margin-bottom: 25px" class="input-group">
        <center>  <%= f.label :avatar, "Avatar:" %>  </center>
        <center>  <%= f.file_field :avatar%>  </center>
        </div>

        <div style="margin-bottom: 25px" class="input-group">
          <%= f.submit "Create my account", class: "btn btn-large btn-primary ", style: "margin-left:5px" %>
        </div>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row" >
  <aside class="span4">
    <section>
      <h1>
        <center>
          <p>
            <%= image_tag @user.avatar.url(:small) %>
          </p>
          <%= @user.name %>
          <%= @user.surname %>
        </center>
      </h1>

      <% if current_user.admin? %>
          <div style= "float:right;margin-right:30%;">
            <%= link_to 'Back', users_path, class: "btn btn-small btn-primary" %>
          </div>
      <% end %>




    </section>
  </aside>
</div>